title: rabeed hassan
logo: WhatsApp Image 2026-01-07 at 15.33.05_10068b6e.jpg
theme: jekyll-theme-minimal
description: >-
   **Data Analyst** | **Power BI** | **Tableau** | **SQL** | **Excel** |
  Helping businesses make data-driven decisions with data visualisation, compelling dashboards.
